const puppeteer = require('puppeteer');
const fs = require('fs');

const companies = [
    "ADPRO SOFTECH PVT LTD",
    "ADRENALIN ESYSTEMS LIMITED",
    "ADV DETAILING AND DESIGN APPLICATIONS INDIA PRIVATE LIMITED",
    "ADPRO SOFTECH PVT LTD",
"ADRENALIN ESYSTEMS LIMITED",
"ADV DETAILING AND DESIGN APPLICATIONS INDIA PRIVATE LIMITED",
"ADVA OPTICAL NETWORKING INDIA PRIVATE LIMITED",
"ADVAITA INDIA CONSULTING PRIVATE LIMITED",
"ADVAIYA SOLUTIONS (P) LTD.",
"ADVANCED BUSINESS & HEALTHCARE SOLUTIONS INDIA PRIVATE LIMITED",
"ADVANCED INVESTMENT MECHANICS INDIA PRIVATE LIMITED",
"ADVANTEST INDIA PRIVATE LIMITED",
"ADVANTMED INDIA LLP",
"ADVANZ PHARMA SERVICES (INDIA) PRIVATE LIMITED",
"ADVARRA INDIA PRIVATE LIMITED",
"ADVISOR360 SOFTWARE PRIVATE LIMITED",
"AECO TECHNOSTRUCT PRIVATE LIMITED",
"AECOM INDIA GLOBAL SERVICES PRIVATE LIMITED",
"AECOR DIGITAL INTERNATIONAL PRIVATE LIMITED",
"AEGIS CUSTOMER SUPPORT SERVICES PVT LTD",
"AEL DATASERVICES LLP",
"AEON COMMUNICATION PRIVATE LIMITED",
"AEREN IP SERVICES PVT. LTD.",
"AEREN IT SOLUTIONS PVT. LTD.",
"AEREON INDIA PRIVATE LIMITED.",
"AEROSPIKE INDIA PRIVATE LIMITED",
"AEXONIC TECHNOLOGIES PRIVATE LIMITED",
"AFFINITY ANSWERS PRIVATE LIMITED",
"AFFINITY GLOBAL ADVERTISING PVT. LTD.",
"AFOUR TECHNOLOGIES PVT. LTD.",
"AGASTHA SOFTWARE PVT. LTD.",
"AGATHSYA TECHNOLOGIES PRIVATE LIMITED",
"AGCO TRADING (INDIA) PRIVATE LIMITED",
"AGGRANDIZE VENTURE PRIVATE LIMITED",
"AGILE ICO PVT LTD",
"AGILE LINK TECHNOLOGIES",
"AGILENT TECHNOLOGIES INTERNATIONAL PVT.LTD.",
"AGILIANCE INDIA PVT LTD",
"AGILITY E SERVICES PRIVATE LIMITED",
"AGILON HEALTH INDIA PRIVATE LIMITED",
"AGNEXT TECHNOLOGIES PRIVATE LTD",
"AGNISYS TECHNOLOGY (P) LTD.",
"AGNITIO SYSTEMS",
"AGNITY COMMUNICATIONS PVT. LTD.",
"AGNITY INDIA TECHNOLOGIES PVT LTD",
"AGNITY TECHNOLOGIES PRIVATE LIMITED",
"AGREETA SOLUTIONS PRIVATE LIMITED",
"AGS HEALTH PVT. LTD",
"AGT ELECTRONICS LTD",
"AGTECHPRO PRIVATE LIMITED",
"AHANA RAY TECHNOLOGIES INDIA PRIVATE LIMITED",
"AI COGITO INDIA PRIVATE LIMITED",
"AI SQUARE GLOBAL SOLUTIONS LLP",
"AIDASTECH INDIA PRIVATE LIMITED",
"AIE FIBER RESOURCE AND TRADING (INDIA) PRIVATE LIMITED",
"AIGENEDGE PRIVATE LIMITED",
"AIGILX HEALTH TECHNOLOGIES PVT LTD",
"AIMBEYOND INFOTECH PRIVATE LIMITED",
"AIML SQUARE PRIVATE LIMITED",
"AIMTRONICS SEMICONDUCTOR INDIA PVT LTD",
"AINS INDIA PVT LTD",
"AINSURTECH PVT LTD",
"AIOPSGROUP COMMERCE INDIA PRIVATE LIMITED",
"AIRAMATRIX PRIVATE LIMITED",
"AIRAVANA SYSTEMS PRIVATE LIMITED",
"AIRBUS GROUP INDIA PVT. LTD.",
"AIRCHECK INDIA PVT. LTD.",
"AIRDATA TECHNOLOGIES PRIVATE LIMITED",
"AIREI INDIA PRIVATE LTD",
"AIRMEET NETWORKS PRIVATE LIMITED",
"AIRO DIGITAL LABS INDIA PRIVATE LIMITED",
"AIRO GLOBAL SOFTWARE PRIVATE LIMITED",
"AIROHA TECHNOLOGY INDIA PRIVATE LIMITED",
"AIRTEL INTERNATIONAL LLP",
"AITHENT TECHNOLOGIES PVT. LTD.",
"AJIRA AI SOFTWARE INDIA PVT LTD",
"AJOSYS TECHNOLOGY SOLUTIONS PVT LTD",
"AJRITH TECH PRIVATE LIMITED",
"AJS SOFTWARE TECHNOLOGIES PRIVATE LIMITED",
"AJUBA COMMERCE PVT. LTD.",
"AK AEROTEK SOFTWARE CENTRE PVT. LTD.",
"AK SURYA POWER MAGIC PVT LTD",
"AKEO SOFTWARE SOLUTIONS PRIVATE LIMITED",
"AKIKO SHERMAN INFOTECH PRIVATE LIMITED",
"AKOTS INDIA PVT. LTD.",
"AKRIDATA INDIA PRIVATE LIMITED",
"AKSA LEGACIES PRIVATE LIMITED",
"AKSHAY RAJENDRA SHANBHAG",
"AKSHAY VANIJYA & FINANCE LTD",
"ALAMY IMAGES INDIA (P) LTD",
"ALAN SOLUTIONS",
"ALATION INDIA PRIVATE LIMITED",
"ALCAX SOLUTIONS",
"ALCODEX TECHNOLOGIES PVT. LTD.",
"ALE INDIA PVT LTD.",
"ALEKHA IT PRIVATE LIMITED",
"ALEPT CONSULTING PRIVATE LIMITED",
"ALERTOPS INDIA PRIVATE LIMITED",
"ALETHEA COMMUNICATIONS TECHNOLOGIES PVT LTD",
"ALFA KPO PVT. LTD.",
"ALFANAR ENGINEERING SERVICES INDIA PVT LTD",
"ALGONICS SYSTEMS PRIVATE LIMITED",
"ALGONOMY SOFTWARE PRIVATE LIMITED",
"ALGORHYTHM TECH PVT LTD"
    // Add all the company names here
];

(async () => {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    const scrapedData = [];

    for (const company of companies) {
        await page.goto('https://www.linkedin.com/', { waitUntil: 'domcontentloaded' });
        await page.waitForSelector('#global-nav-typeahead');
        await page.type('#global-nav-typeahead', company);
        await page.keyboard.press('Enter');
        await page.waitForNavigation({ waitUntil: 'domcontentloaded' });

        const linkedinUrl = await page.evaluate(() => {
            const firstResult = document.querySelector('.search-result__wrapper a');
            return firstResult ? firstResult.href : null;
        });

        scrapedData.push({
            company: company,
            linkedinUrl: linkedinUrl || 'Not found'
        });

        console.log(`Scraped ${company}: ${linkedinUrl || 'Not found'}`);
    }

    await browser.close();

    // Save data to CSV
    const csvData = scrapedData.map(item => `${item.company},${item.linkedinUrl}`).join('\n');
    fs.writeFileSync('scraped_data.csv', csvData);

    console.log('Data saved to scraped_data.csv');
})();
